spring:
  application:
    name: warehouse-service

server:
  port : 8082

udp-messages:
  temp:
    port: 3344
  humidity:
    port: 3355

job:
  nats:
    uri: nats://localhost:4222
    temp-topic-name: TEMP
    humidity-topic-name: HUMIDITY
